WebApplication5/Entities/Category.cs
namespace WebApplication5.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string? Title { get; set; }
    }
}

WebApplication5/Entities/Product.cs
namespace WebApplication5.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public decimal Price { get; set; }
    }
}

WebApplication5/Models/CategoryListViewModel.cs
using WebApplication5.Entities;

namespace WebApplication5.Models
{
    public class CategoryListViewModel
    {
        public List<CategoryViewModel> Categories { get; set; }
    }
}

WebApplication5/Models/CategoryViewModel.cs
namespace WebApplication5.Models
{
    public class CategoryViewModel
    {
        public string? Title { get; set; }
    }
}

WebApplication5/Models/ErrorViewModel.cs
namespace WebApplication5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication5/Models/ProductListViewModel.cs
using WebApplication5.Entities;

namespace WebApplication5.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<ProductViewModel> Products { get; set; }
        public IEnumerable<CategoryViewModel> Categories { get; set; }
    }
}

WebApplication5/Models/ProductViewModel.cs
namespace WebApplication5.Models
{
    public class ProductViewModel
    {
        public string? Name { get; set; }

        public decimal Price { get; set; }
    }
}

WebApplication5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductDbContext _context;

        public HomeController(ProductDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var products = _context.Products.ToList().Select(p =>
            {
                return new ProductViewModel
                {
                    Name = p.Name,
                    Price = p.Price,
                };
            });

            var categories=_context.Categories.ToList().Select(c =>
            {
                return new CategoryViewModel
                {
                    Title = c.Title
                };
            });

            var vm = new ProductListViewModel
            {
                Products = products,
                Categories=categories
            };
            return View(vm);
           

        }
    }
     

}

WebApplication5/Pages/Product/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;

namespace WebApplication5.Pages.Product
{
    public class EditModel : PageModel
    {
        private readonly ProductDbContext _context;

        public EditModel(ProductDbContext context)
        {
            _context = context;
        }
        public List<Entities.Product> Products { get; set; }
        [BindProperty]
        public Entities.Product Product { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = _context.Products.Find(id);

            if (Product == null)
            {
                return NotFound();
            }

            return Page();
        }
        public string Info { get; set; }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var entry = _context.Entry(Product);
            if (entry.State == EntityState.Detached)
            {
                _context.Attach(Product);
                entry.State = EntityState.Modified;
            }

            _context.SaveChanges();
            return RedirectToPage("/Product/Index");
        }

    }
}

WebApplication5/Pages/Product/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication5.Data;

namespace WebApplication5.Pages.Product
{
    public class IndexModel : PageModel
    {
        private readonly ProductDbContext _context;

        public IndexModel(ProductDbContext context)
        {
            _context = context;
        }

        public List<Entities.Product> Products { get; set; }
        public void OnGet(string info = "")
        {
            Products = _context.Products.ToList();
            Info = info;
        }

        public string Info { get; set; }

        [BindProperty]
        public Entities.Product Product { get; set; }

        public IActionResult OnPost()
        {
            _context.Products.Add(Product);
            _context.SaveChanges();
            Info = $"{Product.Name} added successfully";
            return RedirectToPage("Index", new {info=Info});
        }

        public IActionResult OnPostDelete(int id)
        {
            var recentProduct = _context.Products.Find(id);
            if (recentProduct == null)
            {
                return NotFound();
            }

            _context.Products.Remove(recentProduct);
            Info = $"{recentProduct.Name} deleted successfully";
            _context.SaveChanges();

            return RedirectToPage("Index", new { info = Info });
        }
    }
}

WebApplication5/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private readonly ProductDbContext _context;

        public CategoryListViewComponent(ProductDbContext context)
        {
            _context = context;
        }

        public ViewViewComponentResult Invoke()
        {
            var categories= _context.Categories.ToList().Select(c =>
            {
                return new CategoryViewModel
                {
                    Title = c.Title
                };
            });
            return View(
                new CategoryListViewModel
                {
                    Categories=categories.ToList()
                }

                );
        }
    }
}

WebApplication5/Areas/Admin/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section>
    <h2>hello admin module user</h2>
    <hr style="background-color:springgreen;" />
</section>

WebApplication5/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
</head>
<body>
    <h1>Admin Module</h1>
    <main role="main" class="col-md-8 pb-3">
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>

WebApplication5/Pages/Product/Edit.cshtml
@page
@model WebApplication5.Pages.Product.EditModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model.Info != "")
{
    <div class="alert alert-success" role="alert">
        @Model.Info
    </div>
}



<form class="col-5" method="post">
    <input type="hidden" asp-for="Product.Id" />
    <div class="mb-3">
        <label class="form-label">Product Name</label>
        <input asp-for="Product.Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Product Price</label>
        <input asp-for="Product.Price" class="form-control" />
    </div>

    <button type="submit" class="btn btn-success">Update</button>
</form>

WebApplication5/Pages/Product/Index.cshtml
@page
@model WebApplication5.Pages.Product.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Info != "")
{
    <div class="alert alert-success" role="alert">
        @Model.Info
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td scope="row">@item.Id</td>
                <td scope="row">@item.Name</td>
                <td scope="row">@item.Price</td>
                <td scope="row">
                    <a class="btn btn-outline-primary" asp-page="/Product/Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    <form method="post" asp-page-handler="Delete" asp-route-id="@item.Id">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>
                </td>


            </tr>
        }
    </tbody>
</table>


<form class="col-5" method="post">
    <div class="mb-3">
        <label class="form-label">Product Name</label>
        <input asp-for=Product.Name class="form-control"/>
    </div>
    <div class="mb-3">
        <label class="form-label">Product Price</label>
        <input asp-for=Product.Price class="form-control" />
    </div>
   
        <button type="submit" class="btn btn-success">Add New Product</button>
</form>

WebApplication5/Views/Home/Index.cshtml
@model ProductListViewModel

<h1>Products</h1>
@foreach(var item in Model.Products){
    <h2>Name : @item.Name</h2>
    <h2>Price : @item.Price</h2>
}
<hr/>
<h1>Categories</h1>
@foreach (var item in Model.Categories)
{
    <h2>Title : @item.Title</h2>
}

WebApplication5/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<section>
    <h1>Categories</h1>
    <ul class="list-group">

    @foreach (var item in Model.Categories)
    {
        <li class="list-group-item">@item.Title</li>
    }
    </ul>
</section>

WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <main role="main" class="col-md-8 pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>